---
title: "Project Phase 2"
author: "Marion Geary"
date: '2022-03-27'
output: html_document
---



```{r}
library(nflverse)
library(tidymodels)

official_player_stats <- calculate_player_stats(load_pbp(), weekly = TRUE)

player_stats <- load_player_stats(
    seasons = most_recent_season(),
    stat_type = 'offense'
  )

player_stats_kicking <- load_player_stats(
    seasons = most_recent_season(),
    stat_type = 'kicking'
  )

combine <- load_combine(seasons = TRUE)

roster <- load_rosters(seasons = most_recent_season())

team_data <- load_teams()

injuries <- load_injuries()

next_gen_pass <- load_nextgen_stats(
    seasons = most_recent_season(),
    stat_type = 'passing'
  )

next_gen_rec <- load_nextgen_stats(
    seasons = most_recent_season(),
    stat_type = 'receiving'
  )

next_gen_rush <- load_nextgen_stats(
    seasons = most_recent_season(),
    stat_type = 'rushing'
  )

snap_counts <- load_snap_counts(seasons = most_recent_season())

pfr_adv_pass <- load_pfr_advstats(
    seasons = most_recent_season(),
    stat_type = 'pass',
    summary_level = 'week'
  )

pfr_adv_rec <- load_pfr_advstats(
    seasons = most_recent_season(),
    stat_type = 'rec',
    summary_level = 'week'
  )

pfr_adv_rush <- load_pfr_advstats(
    seasons = most_recent_season(),
    stat_type = 'rush',
    summary_level = 'week'
  )

pfr_adv_def <- load_pfr_advstats(
    seasons = most_recent_season(),
    stat_type = 'def',
    summary_level = 'week'
  )
```

Joining time

```{r}
roster_off <- roster %>%
  full_join(
      official_player_stats,
      by = c("gsis_id" = "player_id"),
      suffix = c('', '.off_pl_stat'),
      keep = FALSE,
      na_matches = 'never'
    ) 

roster_off <- roster_off %>%
  distinct() %>%
  select(- (grep(".off_pl_stat", names(roster_off))))

roster_off_pl_kick <- roster_off %>%
  full_join(
      player_stats_kicking,
      by = c("gsis_id" = "player_id", 'week' = 'week'),
      suffix = c('', '.xyz'),
      keep = FALSE
    )
         
roster_off_pl_kick <- roster_off_pl_kick %>%
  distinct() %>%
  select(- (grep(".xyz", names(roster_off_pl_kick))))    

# use official player stats, don't use 'player stats', use player_stats_kick

roster_off_pl_kick_com <- roster_off_pl_kick %>%
  left_join(
      combine,
      by = c('pfr_id' = 'pfr_id'),
      suffix = c('', '.xyz'),
      keep = FALSE,
      na_matches = 'never'
    )

roster_off_pl_kick_com <- roster_off_pl_kick_com %>%
  distinct() %>%
  select(- (grep(".xyz", names(roster_off_pl_kick_com)))) 

injuries <- injuries %>%
  mutate(season = as.numeric(season), week = as.numeric(week))

roster_off_pl_kick_com_team_inj <- roster_off_pl_kick_com %>%
  left_join(
    injuries,
    by = c('gsis_id' = 'gsis_id', 'season' = 'season', 'week' = 'week'),
    suffix = c('', '.xyz'),
    keep = FALSE
  )

roster_off_pl_kick_com_team_inj <- roster_off_pl_kick_com_team_inj %>%
  distinct() %>%
  select(- (grep(".xyz", names(roster_off_pl_kick_com_team_inj)))) 

all_next_gen <- roster_off_pl_kick_com_team_inj %>%
  left_join(
    next_gen_pass,
    by = c('gsis_id' = 'player_gsis_id', 'season' = 'season', 'week' = 'week'),
    suffix = c('', '.xyz'),
    keep = FALSE
  ) %>% left_join(
    next_gen_rec,
    by = c('gsis_id' = 'player_gsis_id', 'season' = 'season', 'week' = 'week'),
    suffix = c('', '.xyz'),
    keep = FALSE
  ) %>% left_join(
    next_gen_rush,
    by = c('gsis_id' = 'player_gsis_id', 'season' = 'season', 'week' = 'week'),
    suffix = c('', '.xyz'),
    keep = FALSE
  )

all_next_gen <- all_next_gen %>%
  distinct() %>%
  select(- (grep(".xyz", names(all_next_gen))))

all_pfr <- all_next_gen %>% left_join(
    pfr_adv_def,
    by = c('pfr_id' = 'pfr_player_id', 'season' = 'season', 'week' = 'week'),
    suffix = c('', '.xyz'),
    keep = FALSE
  ) %>% left_join(
    pfr_adv_pass,
    by = c('pfr_id' = 'pfr_player_id', 'season' = 'season', 'week' = 'week'),
    suffix = c('', '.xyz'),
    keep = FALSE
  ) %>% left_join(
    pfr_adv_rush,
    by = c('pfr_id' = 'pfr_player_id', 'season' = 'season', 'week' = 'week'),
    suffix = c('', '.xyz'),
    keep = FALSE
  ) %>% left_join(
    pfr_adv_rec,
    by = c('pfr_id' = 'pfr_player_id', 'season' = 'season', 'week' = 'week'),
    suffix = c('', '.xyz'),
    keep = FALSE
  )

all_pfr <- all_pfr %>%
  distinct() %>%
  select(- (grep(".xyz", names(all_pfr))))

all_data <- all_pfr %>% left_join(
  snap_counts,
  by = c('pfr_id' = 'pfr_player_id', 'season' = 'season', 'week' = 'week'),
  suffix = c('', '.xyz'),
  keep = FALSE
)

all_data <- all_data %>%
  distinct() %>%
  select(- (grep(".xyz", names(all_data))))

```

```{r}
all_data <- all_data %>%
  select(-c(espn_id, sportradar_id, yahoo_id, rotowire_id, pff_id, pfr_id, fantasy_data_id, sleeper_id, player_name, cfb_id, pos, date_modified, player_display_name, team_abbr, player_position, player_first_name, player_last_name, player_short_name, player_jersey_number, pfr_game_id, season_type, pfr_player_name, player, high_school, fg_made_list, fg_missed_list, fg_blocked_list))

## better way to do this?
all_data <- all_data %>%
  filter(!is.na(fantasy_points_ppr)) %>%
  mutate_if(is.character, as.factor)
```

```{r}
all_data <- all_data %>% select(-c(season, last_name, first_name))

recipe <- all_data %>% recipe(fantasy_points ~ .) %>%
  update_role(gsis_id, game_id, full_name, new_role = "id") %>%
  update_role(headshot_url, new_role = "graphics") %>%
  update_role(fantasy_points_ppr, new_role = "comparison") %>%
  step_normalize(all_numeric_predictors()) %>%
  step_corr(all_numeric_predictors(), threshold = 0.9) %>%
  step_dummy(all_nominal_predictors())


prep <- prep(recipe, all_data)

juice <- juice(prep(recipe, all_data))
```


```{r}
save.image("nfl-project.Rdata")
```



```{r}
calculate_ff_points <- function(all_data) {
  all_data <- all_data %>% mutate_if(is.numeric, ~replace(., is.na(.), 0))
  all_data <- all_data %>% add_column(ff_pts = (all_data$pass_yards / 25) + (all_data$pass_touchdowns * 4) + (all_data$interceptions * -2) + (all_data$passing_2pt_conversions * 2) + (all_data$rush_touchdowns * 6) + (all_data$rush_yards / 10) + (all_data$rushing_2pt_conversions * 2) + (all_data$receiving_tds * 6) + (all_data$receiving_yards / 10) + (all_data$receiving_2pt_conversions * 2) + ((all_data$fg_made_0_19 + all_data$fg_made_20_29 + all_data$fg_made_30_39) * 3) + (all_data$fg_made_40_49 * 4) + (all_data$fg_made_50_59 * 5) + (all_data$fg_made_60_ * 6) + (all_data$pat_made * 1) + (all_data$fg_missed * -1) + ((all_data$sack_fumbles_lost + all_data$rushing_fumbles_lost + all_data$receiving_fumbles_lost) * -2) + (all_data$def_sacks) + (all_data$def_ints * 2))
  return(all_data)
}

calculate_ff_points(all_data) %>% select(ff_pts, fantasy_points) %>% arrange(ff_pts)
```


Graphs

```{r}


all_data %>%
  group_by(gsis_id) %>%
  summarise(mean = mean(fantasy_points)) %>%
  ggplot(aes(x = mean)) +
  geom_histogram() +
  labs(x = 'Average Fantasy Points', y = 'Number of Players', title = 'Average Fantasy Points Per Player')

all_data %>%
  ggplot(aes(x = fantasy_points)) +
  geom_histogram(aes(color = recent_team, fill = recent_team)) +
  facet_wrap(~recent_team) +
  scale_color_nfl(type = 'secondary') +
  scale_fill_nfl() +
  theme(legend.position = 'none') +
  labs(x = 'Fantasy Points', y = 'Count', title = 'Distribution of Fantasy Points by Team')

all_data %>% 
  filter(!is.na(position)) %>%
  ggplot(aes(x = fantasy_points)) + 
  geom_dotplot(color = 'black', alpha = 0.8, aes(fill = position)) +
  facet_wrap(~ position) +
  theme(legend.position = 'none') + 
  labs(x = 'Fantasy Points', y = 'Count', title = 'Distribution of Fantasy Points by Position')
  
all_data %>%
  group_by(gsis_id) %>% 
  summarise(mean = mean(fantasy_points), wopr = mean(wopr, na.rm = T), position = position) %>%
  ggplot(aes(x = mean, y = wopr, color = position)) + 
  geom_jitter(alpha = 0.7) + 
  scale_color_manual(values = c("QB" = 'red',
                                "WR" = 'blue',
                                "RB" = 'yellow',
                                'TE' = 'green'))

all_data %>%
  group_by(gsis_id) %>%
  summarise(mean = mean(fantasy_points), gsis_id = gsis_id, full_name = full_name, headshot_url = headshot_url, position = position) %>%
  filter(mean >= 20) %>%
  ggplot() + 
  geom_col(aes(x = gsis_id, y = mean, color = position)) +
  theme_minimal() + 
  theme(axis.text.x = element_nfl_headshot())


all_data %>%
  summarise(mean = mean(fantasy_points), recent_team = recent_team) %>%
  arrange(mean) %>%
  ggplot(aes(x = recent_team, y = mean)) +
  geom_col(aes(color = recent_team, fill = recent_team), width = 0.5) +
  scale_color_nfl(type = "secondary") +
  scale_fill_nfl(alpha = 0.4) +
  theme_minimal() +
  theme(axis.text.x = element_nfl_logo())
  
colnames(all_data)
```

# Numeric Summary

```{r}
all_data %>%
  group_by(recent_team) %>%
  summarise(
      recent_team = recent_team,
      avg_fantasy_pts = mean(fantasy_points),
      pts_sd = sd(fantasy_points),
      min = min(fantasy_points),
      max = max(fantasy_points)
    ) %>%
  distinct() %>%
  arrange(-avg_fantasy_pts)

pos_levelr <- forcats::fct_lump_min(
    all_data$position, min = 10,
    other_level = "Other"
  )

all_data %>%
  mutate(pos_level = pos_levelr) %>%
  filter(!is.na(pos_level)) %>%
  group_by(pos_level) %>%
  summarise(
      avg_fantasy_pts = mean(fantasy_points),
      number = n()
    ) %>%
  distinct() %>%
  arrange(-avg_fantasy_pts)

all_data %>%
  group_by(gsis_id) %>%
  summarise(
      name = full_name,
      position = position,
      avg_fantasy_pts = mean(fantasy_points)
  ) %>% distinct() %>%
  arrange(-avg_fantasy_pts)

all_data %>%
  summary()
```

```{r}
ff_data <- readr::read_csv('/Users/Marion/Desktop/math386/project/nfl-machine-learning/fantasy_pts.txt')

ff_data <- ff_data %>% mutate_if(is.factor, as.character)

ff_data <- ff_data %>% mutate(Player = stringr::str_replace_all(ff_data$Player, "[:punct:]", ""))

all_data <- lef
```

